language: node_js
node_js:
  - "7"
  - "6"
sudo: enabled
os: osx
before_install:
  - brew install yarn
install:
  - yarn
jobs:
  include:
    - stage: jests
      node_js: "7"
      script: echo "Testing with Jest and Codecov..."
      script: npm run codecov
